# Generated by Django 5.0 on 2024-01-13 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_client_crt_token_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hsmpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MultiTenantName', models.CharField(max_length=80)),
                ('HSM_Pool_Name', models.CharField(max_length=100, unique=True)),
                ('HSM_IP', models.CharField(max_length=100)),
                ('HSM_Port', models.CharField(max_length=100)),
                ('HSM_Status', models.CharField(choices=[('active', 'active'), ('passive', 'passive')], default='passive', max_length=7)),
                ('HSM_Pool_Type', models.CharField(choices=[('single', 'single'), ('multi', 'multi')], max_length=7)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultifactorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keys_Create', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('Valid_Load_Request', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('CA_CRT', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('CRT_Delete_Client', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('crt_load_client', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('CSR_HSM_CRT_Request', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('CA_CRT_Delete', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('Keys_Delete', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('Slot_delete', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('hsm_slot_update', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('Slot_List', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('Pool_Active', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('Pool_delete', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('Pool_create', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('Pool_Upload', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('user_factor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MultiTenantName', models.CharField(max_length=80)),
                ('Rules_Name', models.CharField(max_length=150, unique=True)),
                ('Pool_Name', models.CharField(max_length=150)),
                ('SlotName', models.CharField(max_length=150)),
                ('SlotID', models.IntegerField()),
                ('Certificate_Name', models.CharField(max_length=150)),
                ('Sending_Time', models.DateTimeField()),
                ('Sending_Person', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='slotlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MultiTenantName', models.CharField(max_length=80)),
                ('TokenName', models.CharField(max_length=100, unique=True)),
                ('UserPIN', models.CharField(max_length=100)),
                ('HSM_Pool_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hsmpool')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MultiTenantName', models.CharField(max_length=80)),
                ('SlotID', models.IntegerField()),
                ('Keys_Type', models.CharField(choices=[('AES', 'AES'), ('RSA', 'RSA'), ('EC', 'EC')], max_length=4)),
                ('Keys_Name', models.CharField(max_length=100)),
                ('Key_BIT', models.CharField(choices=[('256', '256'), ('128', '128'), ('512', '512'), ('1024', '1024'), ('2048', '2048'), ('3072', '3072'), ('4096', '4096'), ('ansiX9p192r1', 'ansiX9p192r1'), ('ansiX9p256r1', 'ansiX9p256r1'), ('ansiX9p384r1', 'ansiX9p384r1'), ('brainpoolP192r1', 'brainpoolP192r1'), ('brainpoolP224r1', 'brainpoolP224r1'), ('brainpoolP256r1', 'brainpoolP256r1'), ('brainpoolP320r1', 'brainpoolP320r1'), ('nistp192', 'nistp192'), ('nistp224', 'nistp224'), ('nistp521', 'nistp521'), ('prime192v1', 'prime192v1'), ('prime192v2', 'prime192v2'), ('prime192v3', 'prime192v3'), ('prime256v1', 'prime256v1'), ('prime384v1', 'prime384v1'), ('secp192k1', 'secp192k1'), ('secp192r1', 'secp192r1'), ('secp224r1', 'secp224r1'), ('secp256k1', 'secp256k1'), ('secp256r1', 'secp256r1'), ('secp384r1', 'secp384r1'), ('secp521r1', 'secp521r1')], max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Token_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slotlist')),
            ],
        ),
        migrations.CreateModel(
            name='client_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MultiTenantName', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=100)),
                ('Slot_ID', models.IntegerField()),
                ('KeyName', models.CharField(max_length=100)),
                ('Certificate_Name', models.CharField(max_length=100)),
                ('Data_Start', models.DateField()),
                ('Data_End', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Token_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slotlist')),
            ],
        ),
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MultiTenantName', models.CharField(max_length=80)),
                ('Slot_ID', models.IntegerField()),
                ('KeyName', models.CharField(max_length=100)),
                ('Certificate_Name', models.CharField(max_length=100)),
                ('Data_Start', models.DateField()),
                ('Data_End', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Token_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slotlist')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MultiTenantName', models.CharField(max_length=80)),
                ('UserType', models.CharField(choices=[('Django', 'Django'), ('Ldap', 'Ldap'), ('AD', 'AD')], default='Django', max_length=10)),
                ('TwoFactor', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('telephone_number', models.CharField(max_length=15)),
                ('MulfiFactor', models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=10)),
                ('USerType', models.CharField(choices=[('System_User', 'System_User'), ('Operator_User', 'Operator_User'), ('Client_User', 'Client_User')], default='Client_User', max_length=16)),
                ('OTP_Value', models.CharField(max_length=50)),
                ('QR_Path', models.CharField(max_length=100)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
