# Generated by Django 4.2.6 on 2023-12-27 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_logs_multitenantname'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_crt',
            name='MultiTenantName',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
