# Generated by Django 4.2.6 on 2023-12-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rules_multitenantname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='User_Name',
        ),
    ]
