# Generated by Django 4.2.6 on 2023-12-29 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_logs_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifactormodel',
            name='MultiTenantName',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
