# Generated by Django 4.2.6 on 2024-01-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_multifactormodel_multitenantname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsmpool',
            name='HSM_Pool_Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
