# Generated by Django 4.2.6 on 2024-01-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_hsmpool_hsm_pool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotlist',
            name='TokenName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
