# Generated by Django 4.2.6 on 2024-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_logs_bak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_crt',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
