from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500
from .views import custom_404
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('login/', views.login_index, name='login_index'),
    path('login_return/', views.login, name='login'),
    path('login_message_return/', views.login_message_return, name='login_message_return'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('index/', views.index, name='index'),
    path('accounts/profile/', views.return_index),
    path('index/<int:id>', views.Pool_delete, name='Pool_delete'),
    path('Multifactor_Pool_delete/', views.Multifactor_Pool_delete, name='Multifactor_Pool_delete'),
    path('Slot_List/update/<int:id>', views.hsm_slot_update, name='hsm_slot_update'),
    path('Multifactor_hsm_slot_update/', views.Multifactor_hsm_slot_update, name='Multifactor_hsm_slot_update'),
    path('index/update/<int:id>', views.hsm_pool_update, name='hsm_pool_update'),
    path('Multifactor_hsm_pool_update/', views.Multifactor_hsm_pool_update, name='Multifactor_hsm_pool_update'),
    path('index/active/<str:hsm_pool_name>', views.Pool_Active, name='Pool_Active'),
    path('Multifactor_Pool_Active/', views.Multifactor_Pool_Active, name='Multifactor_Pool_Active'),
    path('', views.index, name='index'),
    path('Multifactor_index/', views.Multifactor_index, name='Multifactor_index'),
    path('logout/', views.logout, name='logout'),
    path('Slot_List/', views.Slot_List, name='Slot_List'),
    path('Multifactor_Slot_List/', views.Multifactor_Slot_List, name='Multifactor_Slot_List'),
    path('Slot_List/<int:id>', views.Slot_delete, name='Slot_delete'),
    path('Multifactor_Slot_delete', views.Multifactor_Slot_delete, name='Multifactor_Slot_delete'),
    path('Certificates_List/', views.Certificates_List, name='Certificates_List'),
    path('Certificates_List/DownloadCRT/<int:id>', views.CRT_Downloads, name='CRT_Downloads'),
    path('Certificates_List/DownloadPublic/<int:id>', views.Public_Downloads, name='Public_Downloads'),
    path('Certificates_List/delete/<int:id>', views.CRT_Delete, name='CRT_Delete'),
    path('Multifactor_CRT_Delete/', views.Multifactor_CRT_Delete, name='Multifactor_CRT_Delete'),
    path('Keys_List/', views.Keys_List, name='Keys_List'),
    path('Multifactor_Keys/', views.Multifactor_Keys, name='Multifactor_Keys'),
    path('Keys_List/<int:id>', views.Keys_delete, name='Keys_delete'),
    path('Multifactor_Keys_Delete/', views.Multifactor_Keys_Delete, name='Multifactor_Keys_Delete'),
    path('Users/', views.Users, name='Users'),
    path('Users/<str:Token_Name>/<str:UserName>', views.hsm_Users_delete, name='hsm_Users_delete'),
    path('csr_create/', views.csr_create, name='csr_create'),
    path('csr_create_new/', views.csr_create_new, name='csr_create_new'),
    path('csr_upload/', views.csr_upload, name='csr_upload'),
    path('Multifactor_csr_upload/', views.Multifactor_csr_upload, name='Multifactor_csr_upload'),
    path('crt_load/', views.crt_load, name='crt_load'),
    path('crt_load_client/', views.crt_load_client, name='crt_load_client'),
    path('Multifactor_crt_load_client/', views.Multifactor_crt_load_client, name='Multifactor_crt_load_client'),
    path('Logs_Views/', views.Logs_views, name='Logs_views'),
    path('Logs_Views/<int:id>', views.Logs_views_number, name='Logs_views_number'),
    path('Logs_CSV/<str:filename>/', views.Single_Backup_CSV, name='Single_Backup_CSV'),
    path('Logs_CSV_Export/', views.export_to_csv, name='export_to_csv'),
    path('register/', views.register, name='register'),
    # path('SSL-offloading/', views.SSL_Offloading, name='SSL_Offloading'),
    # path('SSL-offloading/delete/<int:id>', views.SSL_Rule_Delete, name='SSL_Rule_Delete'),
    # path('offloading/<str:filetype>/Dockerfile', views.Dockerfile_Downloads, name='Dockerfile_Downloads'),
    # path('SSL-offloading/<str:RulesName>', views.NginxConfigDownload, name='NginxConfigDownload'),
    # path('SSL-offloading/SSL/<str:RulesName>', views.NginxSSLDownload, name='NginxSSLDownload'),
    path('Client_Certificate/', views.Client_Cert, name='Client_Cert'),
    path('Client_Certificate/DownloadPublic/<int:id>', views.Public_Downloads_Client, name='Public_Downloads_Client'),
    path('Client_Certificate/DownloadCRT/<int:id>', views.CRT_Downloads_Client, name='CRT_Downloads_Client'),
    path('Client_Certificate/delete/<int:id>', views.CRT_Delete_Client, name='CRT_Delete_Client'),
    path('Multifactor_CRT_Delete_Client/', views.Multifactor_CRT_Delete_Client, name='Multifactor_CRT_Delete_Client'),
    path('profile/', views.profile, name='profile'),
    path('Multifactor_profile_enable/', views.Multifactor_profile_enable, name='Multifactor_profile_enable'),
    path('Multifactor_Multi_enable/', views.Multifactor_Multi_enable, name='Multifactor_Multi_enable'),
    path('Multifactor_profile/', views.Multifactor_profile, name='Multifactor_profile'),
    path('profile/<int:user_id>', views.profile_enable, name='profile_enable'),
    path('profile/multi_factor/<int:user_id>', views.Multi_enable, name='Multi_enable'),
    path('verify_2fa/', views.verify_2fa_view, name='verify_2fa_view'),
    path('export-logs-to-csv/', views.export_logs_to_csv, name='export_logs_to_csv'),
    path('murat/', views.deneme, name='deneme'),
    path('CA_CRT/', views.CA_CRT, name='CA_CRT'),
    path('Multifactor_CA_CRT/', views.Multifactor_CA_CRT, name='Multifactor_CA_CRT'),
    path('Valid_Load_Request/', views.Valid_Load_Request, name='Valid_Load_Request'),
    path('Multifactor_Valid_Load_Request/', views.Multifactor_Valid_Load_Request, name='Multifactor_Valid_Load_Request'),
    path('Valid_Key_CRT/', views.Valid_Key_CRT, name='Valid_Key_CRT'),
    path('HSM_Certificate/', views.HSM_Certificate, name='HSM_Certificate'),
    path('Rules/', views.Rules_view, name='Rules_view'),
    path('Rules/<str:str_name>/', views.Rules_delete, name='Rules_delete'),
    path('Rules/Upload/<str:str_name>/', views.Rules_Upload, name='Rules_Upload'),
    path('Users_All/', views.Users_All, name='Users_All'),
    path('Users_All/<int:id>', views.Users_All_Update, name='Users_All_Update'),
    path('Users_All/Type/<int:id>', views.UserTypeUpdate, name='UserTypeUpdate'),
    path('forgot-password/', views.forgotpassword, name='forgotpassword'),
    path('PasswordChange/<str:Email>/<str:DataEnc>/', views.PasswordChange, name='PasswordChange'),
    path('HSM_Certificate/<str:slot_label>/<int:slot_id>/<str:certificate_name>/', views.HSM_To_Certificate, name='HSM_To_Certificate'),
    path('Dashboard/', views.Dashboard, name='Dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'app.views.custom_404'
handler500 = 'app.views.custom_500'