apiVersion: v1
kind: Service
metadata:
  name: hsm-service
  namespace: tanent-1  # Namespace belirtilmiş
spec:
  selector:
    app: hsm
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
