apiVersion: v1
kind: Secret
metadata:
  name: pki-api-secrets
  namespace: tanent-1
type: Opaque
data:
  PYKCS11LIB: /lib64/libprocryptoki.so
  RabbitUser: bXl1c2Vy   # Base64-encoded myuser
  RabbitPassword: bXlwYXNzd29yZA==   # Base64-encoded mypassword
  RABBITMQ_HOST: cGtpX3JhYmJpdG1x   # Base64-encoded pki_rabbitmq
  Slot_ID: MQ==   # Base64-encoded "1"
  Slot_Key_Name: U2xvdF9FbmNyeXB0X0FFUw==   # Base64-encoded Slot_Encrypt_AES
