apiVersion: v1
kind: Secret
metadata:
  name: pki-alarm-secrets
  namespace: tanent-1
type: Opaque
data:
  Postgresql_User: cG9zdGdyZXM=   # Base64 encoded username 'postgres'
  Postgresql_Password: cG9zdGdyZXM=   # Base64 encoded password 'postgres'
